// 노래 맞히기 곡 목록 (유튜브 공식 뮤직비디오)
// y: 유튜브 영상 주소의 v= 뒤 11글자, t: 들려줄 시작 위치(초, 없으면 45~75초 중 무작위), a: 정답으로 인정할 다른 이름
// 영상이 외부 재생을 막아 두었으면 게임이 자동으로 다음 곡으로 넘어가요. 곡은 자유롭게 추가·삭제해도 돼요.

export const ERAS = {
  '2000': '2000년대',
  '2010': '2010년대',
  '2020': '2020년대',
  latest: '최신 인기곡',
  all: '전체',
};

export const SONGS = {
  '2000': [
    { title: '거짓말', artist: '빅뱅', y: '2Cv3phvP8Ro', a: ['lies'] },
    { title: 'Tell Me', artist: '원더걸스', y: 'bnu9JRdVaNg', a: ['텔미'] },
    { title: 'Gee', artist: '소녀시대', y: 'U7mPqycQ0tQ', a: ['지'] },
    { title: 'Nobody', artist: '원더걸스', y: 'QZBn1e9pr2Q', a: ['노바디'] },
    { title: '하루하루', artist: '빅뱅', y: 'MzCbEdtNbJ0', a: ['haru haru'] },
    { title: "I Don't Care", artist: '2NE1', y: 'ctl6yWe0vwo', a: ['아이돈케어', 'idontcare'] },
    { title: '누난 너무 예뻐', artist: '샤이니', y: 'VTASffPQGhY', a: ['replay', '리플레이', '누난너무예뻐'] },
    { title: 'Abracadabra', artist: '브라운아이드걸스', y: 'OEckS5VkiPs', a: ['아브라카다브라'] },
    { title: '주문', artist: '동방신기', y: 'HtJS32n6LNQ', a: ['mirotic', '미로틱'] },
    { title: 'U-Go-Girl', artist: '이효리', y: 'dvdtN8afDg8', a: ['유고걸', 'ugogirl'] },
    { title: '가시', artist: '버즈', y: 'ZhI9tQP4Abw', a: [] },
    { title: 'Fire', artist: '2NE1', y: 'ISEoXdHb4W4', a: ['파이어'] },
    { title: '마지막 인사', artist: '빅뱅', y: 'PQ3gphHww1Q', a: ['last farewell'] },
    { title: '총 맞은 것처럼', artist: '백지영', y: 'uSdlduWm4HM', a: ['총맞은것처럼'] },
    { title: 'So Hot', artist: '원더걸스', y: 'lmun5PO54VE', a: ['쏘핫', '소핫'] },
    { title: "It's Raining", artist: '비', y: 'j492N1OX47I', a: ['잇츠레이닝', 'itsraining'] },
    { title: '소원을 말해봐', artist: '소녀시대', y: '6SwiSpudKWI', a: ['genie', '지니'] },
  ],
  '2010': [
    { title: '강남스타일', artist: '싸이', y: '9bZkp7q19f0', a: ['gangnam style'] },
    { title: '좋은 날', artist: '아이유', y: 'jeqdYqsrsA0', a: ['좋은날', 'good day'] },
    { title: 'Bad Girl Good Girl', artist: 'miss A', y: '8TeeJvcBdLA', a: ['배드걸굿걸'] },
    { title: '벚꽃 엔딩', artist: '버스커 버스커', y: 'WWO7Rk44C4w', a: ['벚꽃엔딩'] },
    { title: '으르렁', artist: 'EXO', y: 'I3dezFzsNss', a: ['growl'] },
    { title: 'TT', artist: '트와이스', y: 'e8LB3hYOa3c', a: ['티티'] },
    { title: 'CHEER UP', artist: '트와이스', y: 'c7rCyll5AeY', a: ['치어업'] },
    { title: '뚜두뚜두', artist: 'BLACKPINK', y: 'IHNzOHi8sJs', a: ['ddu-du ddu-du', 'ddududdudu'] },
    { title: '위아래', artist: 'EXID', y: 'hfXZ6ydgZyo', a: ['up&down', 'up and down'] },
    { title: '에너제틱', artist: '워너원', y: 'awtuTjNmYkI', a: ['energetic'] },
    { title: '너무너무너무', artist: 'I.O.I', y: 'l1hxg1rY17I', a: ['very very very'] },
    { title: '빨간 맛', artist: '레드벨벳', y: 'WyiIGEHQP8o', a: ['빨간맛', 'red flavor'] },
    { title: '봄날', artist: '방탄소년단', y: 'xEeFrLSkMm8', a: ['spring day'] },
    { title: '작은 것들을 위한 시', artist: '방탄소년단', y: 'XsX3ATc3FbA', a: ['boy with luv', '작은것들을위한시'] },
    { title: '피 땀 눈물', artist: '방탄소년단', y: 'hmE9f-TEutc', a: ['피땀눈물', 'blood sweat & tears', 'blood sweat and tears'] },
    { title: '불타오르네', artist: '방탄소년단', y: '4ujQOR2DMFM', a: ['fire'] },
    { title: '밤편지', artist: '아이유', y: 'BzYnNdJhZQw', a: ['through the night'] },
    { title: '달라달라', artist: 'ITZY', y: 'pNfTK39k55U', a: ['dalla dalla'] },
    { title: '사랑을 했다', artist: 'iKON', y: 'vecSVX1QYbQ', a: ['사랑을했다', 'love scenario'] },
    { title: 'BANG BANG BANG', artist: '빅뱅', y: '2ips2mM7Zqw', a: ['뱅뱅뱅'] },
  ],
  '2020': [
    { title: 'Dynamite', artist: '방탄소년단', y: 'gdZLi9oWNZg', a: ['다이너마이트'] },
    { title: 'How You Like That', artist: 'BLACKPINK', y: 'ioNng23DkIM', a: ['하우유라이크댓'] },
    { title: 'Butter', artist: '방탄소년단', y: 'WMweEpGlu_U', a: ['버터'] },
    { title: 'Next Level', artist: 'aespa', y: '4TWR90KJl84', a: ['넥스트레벨'] },
    { title: 'LOVE DIVE', artist: 'IVE', y: 'Y8JFxS1HlDo', a: ['러브다이브'] },
    { title: 'Hype Boy', artist: 'NewJeans', y: '11cta61wi0g', a: ['하입보이'] },
    { title: 'Attention', artist: 'NewJeans', y: 'js1CtxSY38I', a: ['어텐션'] },
    { title: 'Ditto', artist: 'NewJeans', y: 'pSUydWEqKwE', a: ['디토'] },
    { title: 'OMG', artist: 'NewJeans', y: 'sVTy_wmn5SU', a: ['오엠지'] },
    { title: 'After LIKE', artist: 'IVE', y: 'F0B7HDiY-10', a: ['애프터라이크'] },
    { title: 'TOMBOY', artist: '(여자)아이들', y: 'Jh4QFaPmdss', a: ['톰보이'] },
    { title: '퀸카', artist: '(여자)아이들', y: '7HDeem-JaSY', a: ['queencard'] },
    { title: 'Super Shy', artist: 'NewJeans', y: 'ArmDp-zijuc', a: ['슈퍼샤이'] },
    { title: 'I AM', artist: 'IVE', y: '6ZUIwj3FgUY', a: ['아이엠'] },
    { title: 'ANTIFRAGILE', artist: 'LE SSERAFIM', y: 'pyf8cbqyfPs', a: ['안티프래자일'] },
    { title: 'Seven', artist: '정국', y: 'QU9c0053UAU', a: ['세븐'] },
    { title: '에잇', artist: '아이유', y: 'TgOu00Mf3kI', a: ['eight'] },
    { title: '사건의 지평선', artist: '윤하', y: 'BBdC1rl5sKY', a: ['사건의지평선', 'event horizon'] },
    { title: '롤린', artist: '브레이브걸스', y: '3cZrxpK2EAQ', a: ["rollin'", 'rollin'] },
    { title: 'WANNABE', artist: 'ITZY', y: 'fE2h3lGlOsk', a: ['워너비'] },
  ],
  latest: [
    { title: 'APT.', artist: '로제 & 브루노 마스', y: 'ekr2nIex040', a: ['아파트', 'apt'] },
    { title: 'Supernova', artist: 'aespa', y: 'phuiiNCxRMg', a: ['슈퍼노바'] },
    { title: 'Whiplash', artist: 'aespa', y: 'jWQx2f-CErU', a: ['위플래시', '위플래쉬'] },
    { title: 'Magnetic', artist: '아일릿', y: 'Vk5-c_v4gMU', a: ['마그네틱'] },
    { title: 'Golden', artist: 'HUNTR/X (케이팝 데몬 헌터스)', y: 'yebNIHKAC4A', a: ['골든'] },
    { title: 'like JENNIE', artist: '제니', y: 'JSFG-IE8n_c', a: ['라이크제니', '라이크 제니'] },
    { title: 'How Sweet', artist: 'NewJeans', y: 'Q3K0TOvTOno', a: ['하우스윗'] },
    { title: 'HAPPY', artist: 'DAY6', y: 'VoC5WqOdc1A', a: ['해피'] },
    { title: 'Welcome to the Show', artist: 'DAY6', y: 'RowlrvmyFEk', a: ['웰컴투더쇼'] },
    { title: '내 이름 맑음', artist: 'QWER', y: 'AlirzLFEHUI', a: ['내이름맑음'] },
    { title: '소나기', artist: '이클립스', y: 'fBB4MaBybyg', a: ['sudden shower'] },
    { title: 'REBEL HEART', artist: 'IVE', y: 'g36q0ZLvygQ', a: ['레벨하트'] },
    { title: '나는 아픈 건 딱 질색이니까', artist: '(여자)아이들', y: 'ATK7gAaZTOM', a: ['fate', '나는아픈건딱질색이니까'] },
    { title: 'Small girl', artist: '이영지', y: '11iZcYbq_is', a: ['스몰걸'] },
    { title: 'Love wins all', artist: '아이유', y: 'JleoAppaxi0', a: ['러브윈즈올'] },
  ],
};

export function songsFor(era) {
  if (era === 'all') return Object.values(SONGS).flat();
  return SONGS[era] || SONGS.latest;
}
